version: '3'
services:
  mongo:
    image: mongo:4.2.0
    ports:
      - 27017:27017
  app:
    image: krlsedu/onibus-poa
    ports:
      - 8080:8080
    links:
      - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
    depends_on:
        - mongo