version: '3'
  services:
    mongo:
      image: mongo:4.2.0
      container_name: "mongodb"
      ports:
        - 27017:27017
      command: --smallfiles

    mongo-init:
      build: ./mongo-init
      links:
        - mongoDb

    mongo-client:
      image: mongoclient/mongoclient
      ports:
        - 3000:3000
      environment:
        - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
      links:
        - mongoDb

    # APP ************************************************************
    app:
      image: krlsedu/onibus-poa
      ports:
        - 8080:8080
      links:
        - mongoDb
      environment:
        - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
      entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"