version: '3'
services:
  mongodb:
    image: mongo:4.2.0
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: krlsedu/onibus-poa
    ports:
      - 8080:8080
    depends_on:
      - mongodb